<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" type="text/css" href="asset/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="asset/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="asset/css/gototop.css">
<link rel="stylesheet" type="text/css" href="asset/jarallax/jarallax.css">
<link rel="stylesheet" type="text/css" href="asset/css/swiper-bundle.min.css">
<link rel="stylesheet" type="text/css" href="asset/css/aos.css">
<link rel="stylesheet" type="text/css" href="asset/css/styles.css">
<link rel="stylesheet" type="text/css" href="asset/css/mystyle.css">
<link rel="stylesheet" type="text/css" href="asset/css/myresponsive.css">